name: testing
on: push
jobs:
  test:
    name: Node ${{ matrix.node_version }} testing
    runs-on: macOS-latest
    strategy:
      matrix:
        node_version: [14]
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup node ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}

      - name: install packages
        run: yarn install
